[package]
name = "Neolove"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }
mlua = { version = "0.11.5", features = ["luau"] }
hound = "3.5.1"
futures = "0.3"
